name: astronomy 

on:
  push:
    branches: [ main ]
    paths:
      - 'js/astronomy/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'js/astronomy/**'

  workflow_dispatch:

env:
  NODE_VERSION: '20'
  REGISTRY: https://registry.npmjs.org/
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY }}
          cache: 'npm'
          
      - name: install ephemerides dependencies
        run: npm -w js/ephemerides ci

      - name: build ephemerides
        run: npm -w js/ephemerides run build

      - name: install dependencies
        run: npm -w js/astronomy ci
        
      - name: test
        run: npm -w js/astronomy run test -- --run

      - name: compile
        run: npm -w js/astronomy run build
        
      - name: Conventional Changelog Action
        id: changelog
        if: github.event_name == 'push'
        uses: TriPSs/conventional-changelog-action@84dadaf2c367cb52af02737cd9c7e888807219e7 # v6
        with:
          github-token: ${{ secrets.github_token }}
          preset: "conventionalcommits"
          git-path: "js/astronomy"
          tag-prefix: "astronomy@v"
          version-file: "js/astronomy/package.json"
          output-file: "false"

      - name: Create Release
        uses: comnoco/create-release-action@7dea6dc82ac9d97ced7a764aa82811451bba80e0 # v2.0.5
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: |
            ${{ steps.changelog.outputs.clean_changelog }}

      - name: publish
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm -w js/astronomy publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

